### ISSUE TITLE
Continuous jump

### ISSUE THREAD

**Issue by lyche9** [soft-eng-practicum/ForkKnightGame#1]
PlayerScript (controls Perry's movement, including Jump()) lacks a grounded boolean that would prevent the player from jumping in the middle of a jump. 

Currently the player can instruct Perry to jump before he hits the ground again, allowing rigidBody2D.AddForce() be called in mid-air. (Camera will not follow after a certain y-height, see "Vector2 maxXandY" in CameraFollow script.)

Fix: There is already a GroundCheck GameObject under PerrySprite in the hierarchy. Tag groundsprites as "ground" (or similar) and write an OnCollisionEnter/OnTriggerEnter function which turns a boolean var jumping to false. Add jumping=true; under PlayerScript.Update() in the if(Input.GetKeyDown) statement. Edit the if statement to if(Input.GetKeyDown && !jumping).

**Comment by lyche9** [comment]
To reproduce: Press the up key a lot.

**Comment by JamesVo1** [comment]
won't it be easier to create a ceiling platform, similar to how perry stands on the ground?

**Comment by lyche9** [comment]
He'd still do the up-up-up-up-and-away thing, Just that he'd hit his head on the ceiling after a certain y-height. Maybe a combination would be better--a smoother jump script as well as a max height for the map.

**Comment by lyche9** [comment]
Disabled jump functionality.
