### ISSUE TITLE
Jump Pt 2

### ISSUE THREAD

**Issue by JamesVo1** [soft-eng-practicum/ForkKnightGame#10]
Issue:If enough zombies spawn, perry can sit on top of all of them. Cannot come back down.

What i also noticed is if theres alot, even if theres a visible space, he still can't jump back down. 

Fix: small hitboxes to accurately represent zombies? (but i think we already did that)

**Comment by lyche9** [comment]
For more accurate colliders, use polygon collider instead. The hit box for zombies is basically the image border of the sprite

**Comment by lyche9** [comment]
Fixed: Jump disabled, health system implemented to prevent buildup of zombies.
