### ISSUE TITLE
Perry Weapon(More Visual)

### ISSUE THREAD

**Issue by JamesVo1** [soft-eng-practicum/ForkKnightGame#14]
Reproduce: Stand far to a side, and turn around when an enemy is right next to Perry. Notice that the "fork" goes through the zombie. Normal gameplay, we have the enemies without the pitchfork inside them

**Comment by lyche9** [comment]
This is issue #5

**Comment by cengique** [comment]
james: make sure you post _unreported_ issues

**Comment by JamesVo1** [comment]
broskies, I didn't know they were the same. I just looked at how it was "reproduced" and found a "different" bug. Just reporting what I noticed.
