### ISSUE TITLE
Score serves more as Counter

### ISSUE THREAD

**Issue by notagainjen** [soft-eng-practicum/ForkKnightGame#20]
This is a known issue, but I'm reporting it for reference:

At the moment the score simply counts how many zombies the player has killed.
We should make a reference sheet with how many points each zombie is worth, and possibly combos (similar to what James said in #17 ). Example: Regular Zombies - 1 point, Cow Zombies - 3 points, etc).

**Comment by lyche9** [comment]
FIxed: Enemy health script now includes a point value int to set per class of zombie.
