### ISSUE TITLE
launching zombies with Perry's jump

### ISSUE THREAD

**Issue by ausdong** [soft-eng-practicum/ForkKnightGame#24]
how: sometimes a big zombie will be on top of Perry. I think this happens when a big zombie and other zombies squish you against the wall. turning towards them will cause the big zombie to 'jump' on top of Perry. then I can press jump and it'll launch the zombie really high into the sky
![1](https://cloud.githubusercontent.com/assets/6701396/2688401/58d71d10-c29b-11e3-9cf3-8748ede01d91.gif)

**Comment by cengique** [comment]
Wow, Austin, you're amazing! Nice video!

**Comment by lyche9** [comment]
Implemented health system to prevent zombie builldup.
