### ISSUE TITLE
building issues/instructions/story

### ISSUE THREAD

**Issue by nwkim10** [soft-eng-practicum/ForkKnightGame#26]
going on austins comment about the barn, if you jump high enough the boundary for the barn eventually ends at a limit and perry can actually jump over it and fall below and behind the background platform. If the zombies push perry against the barn long enough he falls through and is perma-stuck below the barn.

also, there should be instructions in-game/some sort of start screen

*will you be setting up a story background for perry?

**Comment by lyche9** [comment]
Noted. It seems like many of these issues stem from the infinite zombie spawn, infinite jump, and infinite health. Looks like we should patch these three bugs first!

I think DeRonne has a story in mind. I'm not sure if we'll have time to "implement" it in the game though. Instructions are on the to-do list.

**Comment by lyche9** [comment]
Disabled jump.
