### ISSUE TITLE
New issue tags ("infinite jump", "infinite health", "infinite spawn", "pitchfork collider", "announcement")

### ISSUE THREAD

**Issue by lyche9** [soft-eng-practicum/ForkKnightGame#27]
Hey guys.

Since we didn't get to scrum or meet yesterday I wanted to make a few comments before Thursday's (possible) scrum:
- The compiled list of issues 1-23 is available on dropbox: https://www.dropbox.com/s/x5prj9ags0m0hxf/IssuesForAssignment.doc I have hard copies in case anyone needs.
- It seems like a lot of the issues being reported are coming from a combination of three main bugs: Perry's infinite jump (i.e. No "grounded" check to prevent him from jumping midair), Perry's infinite health (i.e. Nothing happens to Perry when enemies collide with him.), and the infinite spawn of zombies (i.e. portraying the zombie apocalypse too realistically). 
- I have added some custom labels/tags to more clearly group these issues--most of them in fact, will be solved at the same time we fix those core three bugs, but in case they aren't, it is possible to filter by tags and bug check these issues individually. Please tag your posts so they're easy to find and reference related posts by using "#" + issue number in the Write field.
- In addition to "infinite jump", "infinite health", "infinite spawn", I also made a "announcement" label. I think GitHub  is a great, centralized place for group notes, issue tracking, and code repo/review. It's easy to filter items in the Issues tab by label/date/assignee/etc. Also the posts go straight to your inbox, where you can respond directly by email. (Also there's an app and it's awesome.)

I'm in the process of properly porting the Unity project to Git. (Not sure if just copying and pasting the assets folder works once we all start working on it.) After that, we should be able to resume work on the project.
- Edit: Also added label "pitchfork collider" since the fork's Box/Circle collider areas/existence seem to be causing trouble too.

**Comment by cengique** [comment]
Let me know if you're having trouble adopting GitHub. Copying and pasting into the directory should work, as long as you _add_ new files to git, _commit_ to your local repo, and then _push_ to GitHub.

**Comment by lyche9** [comment]
I think so too. I do have a question though: I used github for a hackathon app last weekend, but every time someone accidentally pushed the bin (binary) files which also changed instead of just the .java class that they were working on, the gitHub "broke" and we had to delete the git directory and re fork/pull from the main repo. The web resources I'm reading mention making a .gitignore file. Does this file prevent these kinds of "random" files from being pushed along with the code or is it for something else?

**Comment by lyche9** [comment]
I think I got it working, but I guess there's not really a way to test until we start coding.

**Comment by cengique** [comment]
in the .gitignore file, you just list patterns of files that should be ignored. So, to ignore .class files, you need a line like this:

```
*.class
```

I don't understand how GitHub broke because of this, any other clues?

**Comment by lyche9** [comment]
I'm not sure. It seemed like our bin files would change themselves so if we tried to push/pull we would end up having conflicts with the main repo.

**Comment by cengique** [comment]
ah, yes, of course. you should have _deleted_ the class files, and then pull. That should solve the problem. This is a common problem with version control. Don't add local files to repos.

**Comment by lyche9** [comment]
I see. So does the .gitignore file help with this or do we have to check by hand each time that we are not pushing any local files?

**Comment by cengique** [comment]
Yes, the .gitignore file helps immensely with this because those files won't show up in your commit list. But anyway, it's always good to be careful with what you're adding/committing to the repo. I never blindly commit; I select each file independently.
