### ISSUE TITLE
We're in buisiness! :D

### ISSUE THREAD

**Issue by lyche9** [soft-eng-practicum/ForkKnightGame#28]
The GitHub repository for the project is officially ready (I hope)! Please delete/remove all other versions of the project that you may have saved previously and clone the repo to your local repository:
1. Make sure you have GitHub installed on your computer.
2. Go to https://github.com/CS370-soft-eng-practicum/ForkKnightGame 
3. Click on "Clone in Desktop" on the bottom right or use the link above the button. 
4. You should be able to open the project through Git Shell, GitHub Desktop App, or through File Explorer/Finder now. 
5. In the Unity project, check under Edit> Project Settings> Editor that "Hidden Metafiles" and "Force Text" are selected. Make sure the project default is "2D".
6. Commit early, commit often.

**Editing and Committing**
After cloning to your desktop, you will be able to edit your personal copy of the project without affecting the main version online. To push (publish) your changes to the main branch (demo_branch1):
1. Sync your copy with the main copy to update it
2. Check that your code still works with the up-to-date version of the project
3. Push your changes (if using desktop app, hit the sync button, type in a commit description, check off  the files you want to push.

I also added a Milestone for v 0.2. You can filter issues by whether or not they're assigned to the milestone as well. Remember to clear the filter(s) if you're trying to view all issues.

Looking forward to assigning issues on Thursday (tomorrow) and getting back to work! :)

**Comment by cengique** [comment]
Don't forget to _add_ new files, _commit_ often locally, and _push_ when you want to publish to others.
