### ISSUE TITLE
Falling through the map

### ISSUE THREAD

**Issue by dstess** [soft-eng-practicum/ForkKnightGame#30]
Using Perry's infinite jump, I moved outside the top of the view on the left side of the level. Instead of dropping down and being blocked by the invisible wall, Perry passed through, disappeared, and then fell through the level.

![screen shot 2014-04-17 at 4 31 23 pm](https://cloud.githubusercontent.com/assets/4603941/2736580/58b80f24-c66f-11e3-9702-0bc3f190335b.png)

**Comment by lyche9** [comment]
Mentioned in #26 . 

> going on austins comment about the barn, if you jump high enough the boundary for the barn eventually ends at a limit and perry can actually jump over it and fall below and behind the background platform

**Comment by dstess** [comment]
![screen shot 2014-04-17 at 4 35 36 pm](https://cloud.githubusercontent.com/assets/4603941/2736627/e6662c16-c66f-11e3-8c5d-c02cb95abc9a.png)

He's a smart peasant.

**Comment by lyche9** [comment]
Disabled jump.
