### ISSUE TITLE
Black top border on left barn

### ISSUE THREAD

**Issue by dstess** [soft-eng-practicum/ForkKnightGame#31]
Only found on the left barn, strangely enough. Photo attached.

![screen shot 2014-04-17 at 4 33 40 pm](https://cloud.githubusercontent.com/assets/4603941/2736599/992c56aa-c66f-11e3-80de-7238511cb383.png)

**Comment by lyche9** [comment]
Mentioned in #29 

> The farm house of the left has a floating black line at the top of it.

and #16 

> Observed: A horizontal grey line appears directly above the barn. This line seems to serve as an indicator of the top of the barn.

However thanks for using a specific title.

**Comment by lyche9** [comment]
Fixed: Set texture/sprite settings to "point".
