### ISSUE TITLE
Background texture issue

### ISSUE THREAD

**Issue by dstess** [soft-eng-practicum/ForkKnightGame#33]
![screen shot 2014-04-17 at 4 38 35 pm](https://cloud.githubusercontent.com/assets/4603941/2736660/60b1bcba-c670-11e3-8afb-83a421930d23.png)

Small section of the orange background that seems out of place.

**Comment by lyche9** [comment]
I don't know if it's worth posting any issues related to the placeholder images, seeing as how we're aiming to replace them all eventually.

**Comment by lyche9** [comment]
Disabled jump functionality.
