### ISSUE TITLE
Game will probably become slow/unresponsive with enough zombies on the screen

### ISSUE THREAD

**Issue by lyche9** [soft-eng-practicum/ForkKnightGame#8]
Currently Perry does not take damage from the zombies, so there is no game over state. If the player lets Perry sit idle for a long period, many zombies will have spawned, which may cause performance issues.

Fix: Make a game over state related to Perry's health.

**Comment by cengique** [comment]
Geez Huili, you found all the bugs yourself? :) Your teammates must be cursing at you because now they have to search for other bugs. :)

**Comment by lyche9** [comment]
All these bugs were caused by missing lines of code/scripts or hastily-finished BoxColliders due to the time constraint. Most of us knew these bugs were present during the first deploy. (e.g. the groundCheck GameObject used to check if Perry is touching the ground is in the project, but we didn't have time to implement the code that would prevent Perry from jumping midair)

I just threw all the ones I could remember onto the list :)

**Comment by lyche9** [comment]
Fixed: Health system implemented, spawners tweaked.
